apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    app: api
    tier: api_replicaset
spec:
  # modify replicas according to your case
  replicas: 4
  selector:
    matchLabels:
      tier: api_replicaset
  template:
    metadata:
      labels:
        tier: api_replicaset
    spec:
      containers:
      - name: api
        image: registry.cluster.wik.cloud/public/echo
        ports:
        - containerPort: 8080